--- #YAML:1.0
name:               Crypt-DSA-GMP
version:            0.01
abstract:           DSA Signatures and Key Generation
author:
    - Dana A Jacobsen <dana@acm.org>
license:            perl_5
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.45
requires:
    base:                 0
    Carp:                 0
    Crypt::Random::Seed:  0
    Data::Buffer:         0.04
    Digest::SHA:          5.22
    Exporter:             5.562
    Math::BigInt:         1.78
    Math::BigInt::GMP:    0
    Math::Prime::Util::GMP:  0.15
    MIME::Base64:         0
    perl:                 5.006002
resources:
    homepage:    https://github.com/danaj/Crypt-DSA-GMP
    repository:  https://github.com/danaj/Crypt-DSA-GMP
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  2
recommends:
    Convert::ASN1:  0
    Convert::PEM:   0.07
